image: python:latest
stages:
  - build
  - test
  - deploy


build-app:
  stage: build
  script:
    - echo "Building app........"
    - docker build -t priyanshu1979/pipeline:01 .

deploy-app:
  stage: deploy
  script:
    - echo "Deploy app......."
    - docker run -d -p 8501:8501 --name myapp  priyanshu1979/pipeline:01
 
  only:
    - main