image: docker:19.03.12
services:
  - docker:19.03.12-bind

stages:
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:01

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-app:
  stage: build
  script:
    - echo "Building app........"
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

deploy-app:
  stage: deploy
  script:
    - echo "Deploy app......."
    # - docker run -d -p 8501:8501 --name myapp  priyanshu1979/pipeline:01
 
  only:
    - main