image: python:latest
stages:
  - build
  - test
  - deploy

before_script:
    - pip install --upgrade pip

build-app:
  stage: build
  script:
    - echo "Building app........"
    - pip install -r requirements.txt

test-app:
  stage: test
  script:
    - echo "Testing app......."
    - mkdir store

deploy-app:
  stage: deploy
  before_script:
    - streamlit --version
  script:
    - echo "Deploy app......."
    - pip install streamlit
    - which py streamlit
    - streamlit run app.py --server.headless true
  artifacts:
    paths:
      - "store"
  only:
    - main