
stages:
  - setup
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:01

before_script:
    - echo "Cleanup......"
    # - apk update
    # - apk add --no-cache bash
    - rm -rf /var/cache/apk/* /tmp/* /var/tmp/*
    
setup:
  image: python:3.9
  stage: setup
  script:
    - apt-get update 
    - apt-get install -y python3 && apt-get install -y python3-pip
    - pip3 install --upgrade pip || true


build-app:
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  stage: build
  script:
    - echo "Building app........"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

deploy-app:
  stage: deploy
  script:
    - echo "Deploy app......."
    # - docker run -d -p 8501:8501 --name myapp  priyanshu1979/pipeline:01
 
  only:
    - main